/** Account roles used for RBAC across Hydromart services (PRD §26). */
export enum Role {
  CUSTOMER = 'CUSTOMER',
  STAFF_DEPOT = 'STAFF_DEPOT',
  KEPALA_DEPOT = 'KEPALA_DEPOT',
  ASSISTANT_SUPERVISOR = 'ASSISTANT_SUPERVISOR',
  SUPERVISOR = 'SUPERVISOR',
  MANAGER = 'MANAGER',
  DIREKTUR = 'DIREKTUR',
  FRANCHISE_OWNER = 'FRANCHISE_OWNER',
  HEAD_OFFICE = 'HEAD_OFFICE',
  FINANCE = 'FINANCE',
  HR = 'HR',
  MARKETING = 'MARKETING',
  SUPER_ADMIN = 'SUPER_ADMIN',
}
