/** Account roles used for RBAC across Hydromart services (PRD §26). */
export enum Role {
  CUSTOMER = 'CUSTOMER',
  DRIVER = 'DRIVER',
  DEPOT_OPERATOR = 'DEPOT_OPERATOR',
  DEPOT_MANAGER = 'DEPOT_MANAGER',
  FRANCHISE_OWNER = 'FRANCHISE_OWNER',
  HEAD_OFFICE = 'HEAD_OFFICE',
  FINANCE = 'FINANCE',
  HR = 'HR',
  MARKETING = 'MARKETING',
  SUPER_ADMIN = 'SUPER_ADMIN',
}
