export const ORDER_TOKENS = {
  CartRepository: Symbol('CartRepository'),
  OutboxRepository: Symbol('OutboxRepository'),
  OrderRepository: Symbol('OrderRepository'),
  SubscriptionRepository: Symbol('SubscriptionRepository'),
  ProductCatalog: Symbol('ProductCatalog'),
  DepotDirectory: Symbol('DepotDirectory'),
  DepotPricing: Symbol('DepotPricing'),
  LoyaltyCoordination: Symbol('LoyaltyCoordination'),
  ReferralCoordination: Symbol('ReferralCoordination'),
  RecommendationCoordination: Symbol('RecommendationCoordination'),
  ForecastCoordination: Symbol('ForecastCoordination'),
  FranchiseRevenue: Symbol('FranchiseRevenue'),
  GallonIssue: Symbol('GallonIssue'),
  CashierShift: Symbol('CashierShift'),
  PaymentReversal: Symbol('PaymentReversal'),
  PaymentCash: Symbol('PaymentCash'),
  DeliverySla: Symbol('DeliverySla'),
  DepotCosts: Symbol('DepotCosts'),
  Membership: Symbol('Membership'),
  ResellerDiscount: Symbol('ResellerDiscount'),
  CustomerDirectory: Symbol('CustomerDirectory'),
  Notification: Symbol('Notification'),
  Promo: Symbol('Promo'),
  Inventory: Symbol('Inventory'),
  MeterReadingRepository: Symbol('MeterReadingRepository'),
} as const;
