-- D3 — the date an employee actually left.
--
-- `contractEndDate` already exists but answers a different question: when a fixed-term
-- contract is DUE to end. It is explicitly documented as "a reminder for HR, not a status
-- change", it is null for every open-ended employee, and it says nothing about someone who
-- resigned in the middle of a month. Payroll needs the day they stopped being owed a wage.
--
-- Nullable, no backfill, no default: an employee who has not left has no exit date, and
-- guessing one from `status = 'RESIGNED'` would invent a day nobody recorded — and that day
-- is a number on a payslip.
--
-- No index, deliberately. Payroll reads this column off an employee row it has already
-- fetched by id; nothing filters or sorts on it. An index here would lock writes on the
-- table for the length of the build (audit H-39) to earn nothing. Add one CONCURRENTLY via
-- scripts/create-indexes.sh on the day a query actually needs it.
ALTER TABLE "employees" ADD COLUMN "exitDate" DATE;
