export const DELIVERY_TOKENS = {
  DeliveryRepository: Symbol('DeliveryRepository'),
  ShiftRepository: Symbol('ShiftRepository'),
  IncidentRepository: Symbol('IncidentRepository'),
  SettlementRepository: Symbol('SettlementRepository'),
  OrderCoordination: Symbol('OrderCoordination'),
  CashCollection: Symbol('CashCollection'),
  CourierPayout: Symbol('CourierPayout'),
  Rating: Symbol('Rating'),
  DepotLocation: Symbol('DepotLocation'),
  OrderPayment: Symbol('OrderPayment'),
  OpsNotifier: Symbol('OpsNotifier'),
  CustomerNotification: Symbol('CustomerNotification'),
  EventPublisher: Symbol('EventPublisher'),
  Storage: Symbol('Storage'),
} as const;
