export const DEPOT_TOKENS = {
  DepotRepository: Symbol('DepotRepository'),
  InventoryRepository: Symbol('InventoryRepository'),
  LowStockAlert: Symbol('LowStockAlert'),
  PricingRuleRepository: Symbol('PricingRuleRepository'),
  GallonReturnRepository: Symbol('GallonReturnRepository'),
  GallonIssueRepository: Symbol('GallonIssueRepository'),
  FranchiseApplicationRepository: Symbol('FranchiseApplicationRepository'),
  PriceOverrideProposalRepository: Symbol('PriceOverrideProposalRepository'),
  IncidentRepository: Symbol('IncidentRepository'),
  ApprovalRepository: Symbol('ApprovalRepository'),
  SupplierRepository: Symbol('SupplierRepository'),
  PurchaseOrderRepository: Symbol('PurchaseOrderRepository'),
  RosterRepository: Symbol('RosterRepository'),
  DepotTargetRepository: Symbol('DepotTargetRepository'),
  CashbookRepository: Symbol('CashbookRepository'),
  DisputeRepository: Symbol('DisputeRepository'),
  MaintenanceRepository: Symbol('MaintenanceRepository'),
  WholesaleTierRepository: Symbol('WholesaleTierRepository'),
  SubscriptionRepository: Symbol('SubscriptionRepository'),
  HuddleRepository: Symbol('HuddleRepository'),
  HandoverRepository: Symbol('HandoverRepository'),
  OperationalReportRepository: Symbol('OperationalReportRepository'),
} as const;
